apiVersion: iotdb.apache.org/v1alpha1
kind: IoTDB
metadata:
  name: iotdb
spec:
  # Add fields here
  sharding:
    - scaleTime: "2018-9-20T00:00:00+08:00"
      schemaSegmentNum: 2
    - scaleTime: "2014-5-14T00:53:28+08:00"
      schemaSegmentNum: 3
  # iotdbImage is the customized docker image repo of IoTDB
  iotdbImage: 2019liurui/iotdb-iotdb:0.9.0-alpine
  # replicaNum is the size of replica
  replicaNum: 0
  # imagePullPolicy is the image pull policy
  imagePullPolicy: Always
  # storageMode can be EmptyDir, HostPath, NFS
  storageMode: EmptyDir
  # hostPath is the local path to store data
  hostPath: /data/iotdb/server
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: iotdb-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: iotdb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 8Gi
  ikrImage: 2019liurui/iotdb-ikr:0.9.0-alpine
  ikrSize: 2
