apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
spec:
  selector:
    app: iotdb
    iotdb_cr: iotdb
  type: NodePort
  ports:
    - port: 6667
      targetPort: 6667
      nodePort: 30080
