apiVersion: v1
kind: Service
metadata:
  name: iotdb-service
  namespace: default
spec:
  selector:
    app: iotdb
    ikr_cr: iotdb
  type: NodePort
  ports:
    - port: 6667
      targetPort: 6667
      nodePort: 30081
