apiVersion: v1
kind: Service
metadata:
  name: ikr-service
  namespace: default
spec:
  selector:
    app: ikr
    ikr_cr: iotdb-ikr
  type: NodePort
  ports:
    - port: 6666
      targetPort: 6666
      nodePort: 30080
