#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function start_sync() {
  echo "SYNC_RECEIVER_ADDRESS=$SYNC_RECEIVER_ADDRESS" >> ./SYNC_RECEIVER_ADDRESS.txt
  SYNC_PERIOD_PARAMETER="sync_period_in_second"
  CUSTOMIZED_SYNC_PERIOD="30"
  sed -i "s/^${SYNC_PERIOD_PARAMETER}.*$/${SYNC_PERIOD_PARAMETER}=${CUSTOMIZED_SYNC_PERIOD}/g" $SYNC_CLINET_CONFIG_FILE
  for LINE in $SYNC_RECEIVER_ADDRESS;
  do
    CHANGE_PARAMETER="server_ip"
    if [ -n "$LINE" ]; then
      if [ "$LINE" != "" ]; then
          sed -i "s/^${CHANGE_PARAMETER}.*$/${CHANGE_PARAMETER}=${LINE}/g" $SYNC_CLINET_CONFIG_FILE
          bash $IOTDB_HOME/tools/start-sync-client.sh > /dev/null 2>&1 &
          sleep 1
          cat $SYNC_CLINET_CONFIG_FILE >> ./SYNC_RECEIVER_ADDRESS.txt
      fi
    fi
  done
}

echo "Applying customized configurations..."
SYNC_CLINET_CONFIG_FILE="$IOTDB_HOME/conf/iotdb-sync-client.properties"
echo $SYNC_CLINET_CONFIG_FILE

if [ $IS_MASTER = "true" ];then
  start_sync
fi



#
#BROKER_ROLE="SLAVE"
#
#if [ $BROKER_ID = 0 ];then
#    if [ $REPLICATION_MODE = "SYNC" ];then
#      BROKER_ROLE="SYNC_MASTER"
#    else
#      BROKER_ROLE="ASYNC_MASTER"
#    fi
#fi
#
##BROKER_NAME=$(cat /etc/hostname)
#DELETE_WHEN="04"
#FILE_RESERVED_TIME="48"
#FLUSH_DISK_TYPE="ASYNC_FLUSH"
#
#function create_config() {
#    rm -f $BROKER_CONFIG_FILE
#    echo "Creating broker configuration."
#    echo "#This file was auto generated by iotdb-operator. DO NOT EDIT." >> $BROKER_CONFIG_FILE
#    echo "brokerClusterName=$BROKER_CLUSTER_NAME" >> $BROKER_CONFIG_FILE
#    echo "brokerName=$BROKER_NAME" >> $BROKER_CONFIG_FILE
#    echo "brokerId=$BROKER_ID" >> $BROKER_CONFIG_FILE
#    echo "deleteWhen=$DELETE_WHEN" >> $BROKER_CONFIG_FILE
#    echo "fileReservedTime=$FILE_RESERVED_TIME" >> $BROKER_CONFIG_FILE
#    echo "brokerRole=$BROKER_ROLE" >> $BROKER_CONFIG_FILE
#    echo "flushDiskType=$FLUSH_DISK_TYPE" >> $BROKER_CONFIG_FILE
#    echo "Wrote broker configuration file to $BROKER_CONFIG_FILE"
#}
#
#
#create_config
